import { Link, useLocation, useNavigate } from "react-router-dom";
import Navbar from "../../components/Navbar.jsx";
import { useEffect } from "react";
import { saveOrder } from "../../data/ordersStore.js";

// Deterministic local QR placeholder (same approach as Payment.jsx) so this
// page never depends on external image URLs.
function buildQrSvg(seedValue) {
  const size = 21;
  let seed = Math.floor(seedValue) % 2147483647;
  if (seed <= 0) seed += 2147483646;
  const rnd = () => {
    seed = (seed * 48271) % 2147483647;
    return seed % 2;
  };
  const cells = [];
  const isFinder = (r, c) => {
    const inTrim = (rr, cc) => {
      if (r < rr || r >= rr + 7 || c < cc || c >= cc + 7) return 0;
      const x = r - rr, y = c - cc;
      if (x === 0 || x === 6 || y === 0 || y === 6) return 1;
      if (x >= 2 && x <= 4 && y >= 2 && y <= 4) return 1;
      return 0;
    };
    return inTrim(0, 0) || inTrim(0, size - 7) || inTrim(size - 7, 0);
  };
  for (let r = 0; r < size; r++) {
    for (let c = 0; c < size; c++) {
      cells.push(isFinder(r, c) || rnd());
    }
  }
  const rects = cells
    .map((on, i) => {
      if (!on) return "";
      const r = Math.floor(i / size), c = i % size;
      return '<rect x="' + c + '" y="' + r + '" width="1" height="1"/>';
    })
    .join("");
  return '<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 21 21"><rect width="21" height="21" fill="#ffffff"/>' + rects + "</svg>";
}

/**
 * Display label / sub-line / status per payment method.
 * Cash stays "Payment Pending" because it is collected at the canteen,
 * while UPI / Card / Wallet were paid online.
 */
function paymentInfo(method, upiId) {
  switch (method) {
    case "card":
      return { label: "Credit / Debit Card", sub: "Visa / Mastercard / RuPay", status: "Paid Successfully", paid: true };
    case "wallet":
      return { label: "Campus Wallet", sub: "Cafe Q Campus Wallet", status: "Paid Successfully", paid: true };
    case "upi":
      return { label: "UPI", sub: upiId || "Paid via UPI", status: "Paid Successfully", paid: true };
    default:
      return { label: "Cash Payment", sub: "Pay at the canteen", status: "Payment Pending", paid: false };
  }
}

// Success copy depends on how the customer is paying (cash must NOT say paid).
function successMessage(method) {
  switch (method) {
    case "card":
      return "Your card payment was successful and your order is confirmed.";
    case "wallet":
      return "Your Campus Wallet payment was successful and your order is confirmed.";
    case "upi":
      return "Your UPI payment was received and your order is confirmed.";
    default:
      return "Your order has been placed successfully. Please pay in cash when collecting your order.";
  }
}

function OrderSuccess() {
  const navigate = useNavigate();
  // Everything about this order arrives from the Payment page via
  // navigate(..., { state }); safe fallbacks keep direct visits working.
  const { state } = useLocation();
  const method = state?.paymentMethod || "cash";
  const items = Array.isArray(state?.cartItems) ? state.cartItems : [];
  const itemCount = items.reduce((sum, i) => sum + (i.quantity || 1), 0);
  const subtotal = state?.subtotal ?? 0;
  const platformFee = state?.platformFee ?? 0;
  const discount = state?.discount ?? 0;
  const total = state?.total ?? 0;
  const slot = state?.selectedSlot || "";
  const upiId = state?.upiId || "";
  const canteenName = state?.canteen?.name || "Campus Bites";

  // Order id is generated by the Payment flow and passed through router state.
  const orderId = state?.orderId ? "#" + state.orderId : "";

  const pay = paymentInfo(method, upiId);
  const message = successMessage(method);
  const qrImg = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(buildQrSvg(orderId.length * 7919));

  // Persist the confirmed order locally (same localStorage mechanism as the
  // cart) so My Orders and Order Details can display it later. Skipped on
  // direct visits that carry no real order payload.
  useEffect(() => {
    if (!state?.orderId || !Array.isArray(state?.cartItems)) return;
    try {
      saveOrder({
        orderId: String(state.orderId),
        placedAt: new Date().toISOString(),
        status: "upcoming",
        paymentMethod: state.paymentMethod,
        total: state.total,
        subtotal: state.subtotal,
        platformFee: state.platformFee,
        discount: state.discount,
        cartItems: state.cartItems,
        selectedSlot: state.selectedSlot,
        canteen: state.canteen ?? { name: canteenName },
        upiId: state.upiId,
      });
    } catch {
      // Ignore persistence failures — the confirmation screen still works.
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state]);

  return (
    <div className="bg-background text-on-surface font-body-md min-h-screen flex flex-col">
      {/* TopNavBar (same Cafe Q navbar as Checkout / Payment) */}
            {/* Shared Cafe Q Navbar */}
            <Navbar />

      <main className="flex-grow w-full max-w-[1240px] mx-auto px-container-padding py-stack-lg flex flex-col gap-stack-lg">
          {/* Stepper: Steps 1-2 completed, Step 3 active */}
          <div className="relative flex items-center justify-between w-full max-w-3xl mx-auto h-20 mt-2">
            <div className="absolute top-1/2 left-0 w-1/2 h-[3px] bg-primary -translate-y-1/2 z-0"></div>
            <div className="absolute top-1/2 left-1/2 w-1/2 h-[3px] bg-primary -translate-y-1/2 z-0"></div>

            {/* Step 1: Checkout (Completed) */}
            <div className="relative z-10 flex flex-col items-center">
              <div className="w-12 h-12 rounded-full bg-primary text-on-primary flex items-center justify-center shadow-md">
                <span className="material-symbols-outlined text-[20px]">check</span>
              </div>
              <span className="absolute -bottom-8 whitespace-nowrap text-label-md font-semibold text-primary">Checkout</span>
            </div>

            {/* Step 2: Payment (Completed) */}
            <div className="relative z-10 flex flex-col items-center">
              <div className="w-11 h-11 rounded-full bg-primary text-on-primary flex items-center justify-center shadow-md">
                <span className="material-symbols-outlined text-[18px]">check</span>
              </div>
              <span className="absolute -bottom-8 whitespace-nowrap text-label-md font-semibold text-primary">Payment</span>
            </div>

            {/* Step 3: Order Success (Active) */}
            <div className="relative z-10 flex flex-col items-center">
              <div className="w-12 h-12 rounded-full bg-primary text-on-primary flex items-center justify-center font-bold shadow-md">3</div>
              <span className="absolute -bottom-8 whitespace-nowrap text-label-md font-bold text-primary">Order Success</span>
            </div>
          </div>

          {/* Hero Section */}
          <section className="text-center flex flex-col items-center gap-4 mt-4">
            <div className="w-24 h-24 bg-green-100 rounded-full flex items-center justify-center shadow-inner">
              <span className="material-symbols-outlined text-green-600 text-[56px]" style={{ color: '#16a34a' }}>check_circle</span>
            </div>
            <h1
              className="text-headline-lg md:text-[40px] font-extrabold tracking-tight"
              style={{ color: '#003e6f', opacity: 1 }}
            >
              Yay! Your Order is Confirmed! 🎉
            </h1>
            <p className="text-on-surface-variant text-lg max-w-2xl">
              Thanks for ordering with Cafe Q.
              <br />
              {message}
            </p>
          </section>

          {/* Info Cards: Order ID + Estimated Ready Time */}
          <section className="flex flex-col sm:flex-row justify-center gap-stack-lg">
            <div className="bg-white border border-outline-variant rounded-2xl p-6 flex items-center gap-5 shadow-sm w-full sm:w-80">
              <div className="bg-surface-container-low p-4 rounded-xl text-primary">
                <span className="material-symbols-outlined text-[28px]">description</span>
              </div>
              <div>
                <p className="text-sm text-on-surface-variant font-medium mb-1">Order ID</p>
                <p className="text-lg font-bold text-on-surface">{orderId || "—"}</p>
              </div>
            </div>
            <div className="bg-white border border-outline-variant rounded-2xl p-6 flex items-center gap-5 shadow-sm w-full sm:w-96">
              <div className="bg-surface-container-low p-4 rounded-xl text-primary">
                <span className="material-symbols-outlined text-[28px]">schedule</span>
              </div>
              <div>
                <p className="text-sm text-on-surface-variant font-medium mb-1">Estimated Ready Time</p>
                <p className="text-lg font-bold text-green-600">{slot || "—"}</p>
              </div>
            </div>
          </section>

          {/* Notification Strip */}
          <div className="bg-green-50 border border-green-200 rounded-xl p-4 text-center text-green-700 text-base font-semibold flex items-center justify-center gap-3 max-w-2xl mx-auto w-full shadow-sm">
            <span className="material-symbols-outlined">notifications_active</span>
            <span>We'll notify you when your food is ready for pickup.</span>
          </div>

          {/* Main Content: Order Details | Summary + Payment Method */}
          <div className="grid grid-cols-1 lg:grid-cols-5 gap-stack-lg">
            {/* Left: Order Details */}
            <div className="lg:col-span-3 bg-white rounded-3xl shadow-sm border border-outline-variant p-8 flex flex-col">
              <div className="flex items-center gap-4 mb-6 pb-5 border-b border-outline-variant">
                <span className="material-symbols-outlined text-primary text-[28px]">description</span>
                <h2 className="text-2xl font-bold text-on-surface">Order Details</h2>
              </div>

              {items.length === 0 ? (
                <p className="text-sm text-on-surface-variant py-8 text-center">No items found for this order.</p>
              ) : (
                <div className="flex-grow flex flex-col gap-6">
                  {items.map((item) => (
                    <div key={item.cartItemId} className="flex items-center justify-between gap-4 py-1 border-b border-dashed border-outline-variant pb-5 last:border-0 last:pb-0 flex-wrap sm:flex-nowrap">
                      <div className="flex items-center gap-4 min-w-0">
                        {item.image ? (
                          <img className="w-20 h-20 rounded-xl object-cover bg-surface-container shadow-sm flex-shrink-0" alt={item.name} src={item.image} />
                        ) : (
                          <div className="w-20 h-20 rounded-xl bg-surface-container shadow-sm flex items-center justify-center flex-shrink-0">
                            <span className="material-symbols-outlined text-on-surface-variant">restaurant</span>
                          </div>
                        )}
                        <div className="flex flex-col min-w-0">
                          <h4 className="font-bold text-on-surface text-lg truncate">{item.name}</h4>
                          <p className="text-sm text-on-surface-variant mt-1 truncate">
                            {item.portion}
                            {item.extras && item.extras.length > 0
                              ? " · " + item.extras.map((e) => e.label).join(", ")
                              : ""}
                          </p>
                          <p className="text-primary mt-1 font-medium">₹{item.unitPrice}</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-4 sm:gap-6">
                        <span className="px-3 py-1.5 bg-surface-container-low border border-outline-variant rounded-lg text-on-surface-variant font-semibold">× {item.quantity}</span>
                        <span className="text-on-surface font-bold text-xl min-w-[64px] text-right">₹{(item.unitPrice || 0) * (item.quantity || 1)}</span>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Order total footer */}
              <div className="mt-6 pt-5 border-t border-outline-variant flex justify-between items-center -mx-8 -mb-8 px-8 py-6 rounded-b-3xl bg-surface-container-low">
                <span className="text-on-surface font-bold text-xl">
                  Total <span className="text-on-surface-variant text-base font-normal ml-2">({itemCount} item{itemCount === 1 ? "" : "s"})</span>
                </span>
                <span className="text-primary font-bold text-3xl">₹{total}</span>
              </div>
            </div>

            {/* Right: Summary + Payment Method */}
            <div className="lg:col-span-2 flex flex-col gap-stack-lg">
              {/* Payment Summary */}
              <div className="bg-white rounded-3xl shadow-sm border border-outline-variant p-8">
                <div className="flex items-center gap-4 mb-6 pb-5 border-b border-outline-variant">
                  <span className="material-symbols-outlined text-primary text-[28px]">receipt_long</span>
                  <h2 className="text-2xl font-bold text-on-surface">Payment Summary</h2>
                </div>
                <div className="space-y-4">
                  <div className="flex justify-between text-on-surface-variant">
                    <span>Subtotal ({itemCount} item{itemCount === 1 ? "" : "s"})</span>
                    <span className="font-medium text-on-surface">₹{subtotal}</span>
                  </div>
                  <div className="flex justify-between text-on-surface-variant">
                    <span>Platform Fee</span>
                    <span className="font-medium text-on-surface">₹{platformFee}</span>
                  </div>
                  <div className="flex justify-between font-medium text-green-600">
                    <span>Discount</span>
                    <span>- ₹{discount}</span>
                  </div>
                </div>
                <div className="mt-6 pt-5 border-t border-outline-variant flex justify-between items-center">
                  <span className="text-on-surface font-bold text-lg">Total Amount Paid</span>
                  <span className="text-primary font-bold text-2xl">₹{total}</span>
                </div>
              </div>

              {/* Payment Method */}
              <div className="bg-white rounded-3xl shadow-sm border border-outline-variant p-8">
                <div className="flex items-center gap-4 mb-6 pb-5 border-b border-outline-variant">
                  <span className="material-symbols-outlined text-primary text-[28px]">credit_card</span>
                  <h2 className="text-2xl font-bold text-on-surface">Payment Method</h2>
                </div>
                <div className="flex items-center justify-between gap-4">
                  <div className="flex items-center gap-4 min-w-0">
                    <div className="w-14 h-10 border border-outline-variant rounded-lg flex items-center justify-center p-1.5 bg-white shadow-sm flex-shrink-0">
                      <span className="material-symbols-outlined text-primary text-[20px]">
                        {pay.paid ? "check_circle" : "payments"}
                      </span>
                    </div>
                    <div className="min-w-0">
                      <p className="font-bold text-on-surface">{pay.label}</p>
                      <p className="text-sm text-on-surface-variant truncate">{pay.sub}</p>
                    </div>
                  </div>
                  <div className="text-right flex-shrink-0">
                    <p className="font-bold text-on-surface text-lg">₹{total}</p>
                    {pay.paid ? (
                      <div className="inline-flex items-center gap-1.5 mt-1 bg-green-50 text-green-700 border border-green-200 px-2.5 py-1 rounded-md text-xs font-bold">
                        <span className="material-symbols-outlined text-[14px]">check</span>
                        <span>{pay.status}</span>
                      </div>
                    ) : (
                      <div className="inline-flex items-center gap-1.5 mt-1 bg-amber-50 text-amber-700 border border-amber-200 px-2.5 py-1 rounded-md text-xs font-bold">
                        <span className="material-symbols-outlined text-[14px]">schedule</span>
                        <span>{pay.status}</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Digital Order Token */}
          <div className="bg-white rounded-3xl p-8 md:p-10 border border-outline-variant shadow-sm relative overflow-hidden">
            <div className="absolute inset-0 bg-surface-container-low opacity-40 pointer-events-none"></div>
            <div className="relative flex flex-col md:flex-row items-center justify-between gap-8">
              <div className="flex flex-col sm:flex-row items-center gap-8 w-full md:w-auto">
                <div className="w-40 h-40 flex-shrink-0 bg-white p-3 rounded-2xl shadow-sm border border-outline-variant">
                  <img alt="QR Code Token" className="w-full h-full object-contain" src={qrImg} />
                </div>
                <div className="text-center sm:text-left">
                  <h3 className="text-primary font-bold text-2xl mb-2">Your Digital Order Token</h3>
                  <p className="text-on-surface font-bold text-xl flex items-center justify-center sm:justify-start gap-2 mb-3">
                    Your order is being prepared
                    <span className="material-symbols-outlined text-primary text-[24px]">soup_kitchen</span>
                  </p>
                  <p className="text-on-surface-variant max-w-md">
                    Show this QR code at the counter to collect your order when your number is called.
                  </p>
                </div>
              </div>
              <div className="flex flex-col gap-4 w-full md:w-auto z-10">
                <button
                  type="button"
                  onClick={() =>
                    navigate("/ticket-details", {
                      state: {
                        orderId: orderId.replace("#", ""),
                        paymentMethod: method,
                        total,
                        cartItems: items,
                        subtotal,
                        platformFee,
                        discount,
                        selectedSlot: slot,
                        canteen: state?.canteen ?? { name: canteenName },
                        upiId: state?.upiId,
                      },
                    })
                  }
                  className="bg-primary hover:bg-primary/90 text-on-primary font-bold py-4 px-8 rounded-xl transition-colors flex items-center justify-center gap-3 w-full md:w-72 shadow-md cursor-pointer"
                >
                  <span className="material-symbols-outlined text-[22px]">receipt</span>
                  View Digital Bill
                </button>
                <Link
                  to="/my-orders"
                  className="bg-white border-2 border-primary text-primary hover:bg-surface-container-low font-bold py-4 px-8 rounded-xl transition-colors flex items-center justify-center gap-3 w-full md:w-72"
                >
                  Go to My Orders
                  <span className="material-symbols-outlined text-[20px]">arrow_forward</span>
                </Link>
              </div>
            </div>
          </div>

          {/* Support Banner */}
          <div className="bg-white rounded-2xl border border-outline-variant p-6 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-sm">
            <div className="flex items-center gap-4 text-on-surface">
              <div className="bg-surface-container-low p-3 rounded-full text-primary">
                <span className="material-symbols-outlined">support_agent</span>
              </div>
              <span className="font-semibold">Need help? Contact our support team</span>
            </div>
            <a
              className="flex items-center gap-2 text-primary font-bold hover:underline text-lg"
              href="tel:+919876543210"
            >
              <span className="material-symbols-outlined">call</span>
              +91 98765 43210
            </a>
          </div>
        </main>
      </div>
  );
}

export default OrderSuccess;